version: '3'
services:
  ocsinventory:
    image: ocsinventory/ocsinventory-docker-image:latest
    container_name: ocsinventory-server
    environment:
      OCS_DBNAME: ocs
      OCS_DBSERVER_READ: ocsinventory-db
      OCS_DBSERVER_WRITE: ocsinventory-db
      OCS_DBUSER: ocs
      OCS_DBPASS: ocs
    volumes:
      - ocssrv:/usr/share/ocsinventory-reports/
      - ocssrv:/etc/ocsinventory-reports/
      - ocssrv:/var/lib/ocsinventory-reports/
    links:
      - db
    ports:
      - 8080:80

  php:
    build:
      context: .
      dockerfile: Dockerfile-glpi
    container_name: glpi-server
    volumes:
      - ./glpi:/var/www/html
    links:
      - db
      - ocsinventory

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./glpi:/var/www/html
    links:
      - php
      - db
      - ocsinventory

  db:
    image: mysql:5.7
    container_name: ocsinventory-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ocs
      MYSQL_PASSWORD: ocs
      MYSQL_DATABASE: ocs
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - ocsdata:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  ocsdata:
    driver: local
  ocssrv:
    driver: local
