FROM php:7.0-fpm
MAINTAINER Alex Komis <oleksandr.komisaruk@brain-agency.com>

# ENV COMPOSER_ALLOW_SUPERUSER=1

# Install dependencies
RUN apt-get update && apt-get install -y \
	zip \
	unzip \
	vim \
	libfreetype6-dev \
    	libjpeg62-turbo-dev \
    	libmcrypt-dev \
    	libpng12-dev \
    	libfcgi0ldbl && \
	docker-php-ext-install -j$(nproc) gd mysqli

# www.conf
RUN sed 's/;ping.path = \/ping/ping.path = \/ping/' -i /usr/local/etc/php-fpm.d/www.conf

# Installing composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Create app dir
RUN mkdir -p /var/www/html
WORKDIR /var/www/html

# Entry point
EXPOSE 9000
CMD composer install --no-dev && php-fpm
# CMD ["php-fpm"]
